---
- hosts: all
  roles:
    - osx-preferences
    - profile-d
  # http://www.nickhammond.com/automating-development-environment-ansible/
  tasks:  
    - name: homebrew Cask installs
      environment: {PATH: '/usr/local/bin:{{ ansible_env.PATH }}'}
      shell: /usr/local/bin/brew cask install {{ item }} --appdir=/Users/{{ ansible_env.USER }}/Applications
      with_items:
        - adium
        - aquamacs
        # TODO: Automate installation of Aquamacs command-line tools too
        - basictex
        - box-sync
        - caffeine
        - dash
        - disk-inventory-x
        - divvy
        - dropbox
        - emacs
        - evernote
        - firefox
        - google-chrome
        - gpgtools
        - kindle
        - limechat
        - onepassword
        - quicksilver
        - rescuetime
        - rdio
        - seashore
        - skitch
        - skype
        - the-unarchiver
        - viscosity
        - vlc
        - wireshark
        - xquartz
        - zotero

    - name: Install libraries with homebrew
      homebrew: name={{ item }} state=present
      with_items:
        - chicken
        - dos2unix
        - elinks
        - git
        - gnu-tar
        - gnupg
        - go
        - heroku-toolbelt
        - httpie
        - ispell
        - lesspipe
        - mobile-shell
        - mono
        - ngrok
        - node
        - pandoc
        - tiger-vnc
        - typesafe-activator
        - wget
        - xmlstarlet

    - name: Install npm packages
      npm: name={{ item }} global=yes state=present
      with_items:
        - keybase-installer
        - azure-cli

    - name: Install gems
      gem: name={{ item }} state=present
      with_items:
        - foreman
