---
- hosts: all
  roles:
    - osx-preferences
    - profile-d
  # http://www.nickhammond.com/automating-development-environment-ansible/
  tasks:  
    - name: Install libraries with homebrew
      homebrew: name={{ item }} state=present
      with_items:
        - chicken
        - git
        - go
        - gnupg
        - heroku-toolbelt
        - ispell
        - mobile-shell
        - node
        - tiger-vnc
        - wget

    - name: Install npm packages
      npm: name={{ item }} global=yes state=present
      with_items:
        - keybase-installer

    - name: Install gems
      gem: name={{ item }} state=present
      with_items:
        - foreman

    - name: Cask installs
      environment: {PATH: '/usr/local/bin:{{ ansible_env.PATH }}'}
      shell: /usr/local/bin/brew cask install {{ item }} --appdir=/Users/{{ ansible_env.USER }}/Applications
      with_items:
        - adium
        - basictex
        - caffeine
        - dash
        - disk-inventory-x
        - divvy
        - dropbox
        - emacs
        - evernote
        - firefox
        - google-chrome
        - gpgtools
        - kindle
        - limechat
        - onepassword
        - quicksilver
        - rdio
        - seashore
        - skitch
        - skype
        - the-unarchiver
        - viscosity
        - vlc
        - wireshark
