---
- hosts: localhost
  roles:
     - homebrew
     - homebrew-cask
  tasks:  
    - name: Install pip packages
      pip: name={{ item }} state=present
      with_items:
        - virtualenv
        - flake8
        - bpython
      sudo: yes
